verbose            = 1
simfake            = 1
module             = "ec20"

[serial]
serial_max         = 8
cmd_timeout        = 3
cmd_timewait_ms    = 500

[produce]
cold_reset_timeout = 0
hot_reset_timeout  = 0
creg_timeout       = 3
common_timeout     = 1